%this file will display a simplified result of the third order constraint.
clear all;
close all;
syms y p dy dp ddy ddp dddy dddp sqrb b pb ppb real;
sys=(ddy*p+dy*dp+ddp*y+dy*dp)*sqrb*pb/2+...
(dy*p+dp*y)*ppb*sqrb/2+...
(dddy*p+ddy*dp)*sqrb*b+...
(2*ddp*dy+2*dp*ddy+dddp*y+ddp*dy)*sqrb*b+...
(ddy*p+2*dy*dp+ddp*y)*sqrb*pb;
disp(simplify(sys));
